services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DOCKER_VOLUME_ROOT}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lakefs"]
      interval: 10s
      timeout: 5s
      retries: 5

  lakefs:
    image: treeverse/lakefs:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LAKEFS_LOGGING_LEVEL=${LAKEFS_LOGGING_LEVEL}
      - LAKEFS_DATABASE_TYPE=${LAKEFS_DATABASE_TYPE}
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - LAKEFS_BLOCKSTORE_TYPE=${LAKEFS_BLOCKSTORE_TYPE}
      - LAKEFS_BLOCKSTORE_LOCAL_PATH=${LAKEFS_BLOCKSTORE_LOCAL_PATH}
      - LAKEFS_STATS_ENABLED=${LAKEFS_STATS_ENABLED}
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ${DOCKER_VOLUME_ROOT}/lakefs:/data/lakefs

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.6.0
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_DEFAULT_ARTIFACT_ROOT: ${MLFLOW_DEFAULT_ARTIFACT_ROOT}
    volumes:
      - ./../../artifacts/mlflow:/mlflow/artifacts
      - ${DOCKER_VOLUME_ROOT}/mlflow:/mlflow
    ports:
      - "5050:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri ${MLFLOW_BACKEND_STORE_URI}
      --default-artifact-root ${MLFLOW_DEFAULT_ARTIFACT_ROOT}

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DOCKER_VOLUME_ROOT}/redis:/data
